// Code generated by protoc-gen-go.
// source: metric.proto
// DO NOT EDIT!

/*
Package metric is a generated protocol buffer package.

It is generated from these files:
	metric.proto

It has these top-level messages:
	ApplicationMetric
	SystemMetric
	Metric
*/
package metric

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ApplicationMetric struct {
	Error []*ApplicationMetric_Error `protobuf:"bytes,1,rep,name=error" json:"error,omitempty"`
	Http  *ApplicationMetric_HTTP    `protobuf:"bytes,2,opt,name=http" json:"http,omitempty"`
	User  []*ApplicationMetric_User  `protobuf:"bytes,3,rep,name=user" json:"user,omitempty"`
}

func (m *ApplicationMetric) Reset()                    { *m = ApplicationMetric{} }
func (m *ApplicationMetric) String() string            { return proto.CompactTextString(m) }
func (*ApplicationMetric) ProtoMessage()               {}
func (*ApplicationMetric) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ApplicationMetric) GetError() []*ApplicationMetric_Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *ApplicationMetric) GetHttp() *ApplicationMetric_HTTP {
	if m != nil {
		return m.Http
	}
	return nil
}

func (m *ApplicationMetric) GetUser() []*ApplicationMetric_User {
	if m != nil {
		return m.User
	}
	return nil
}

type ApplicationMetric_Breadcrumb struct {
	Crumb []*ApplicationMetric_BreadcrumbDetail `protobuf:"bytes,1,rep,name=crumb" json:"crumb,omitempty"`
}

func (m *ApplicationMetric_Breadcrumb) Reset()                    { *m = ApplicationMetric_Breadcrumb{} }
func (m *ApplicationMetric_Breadcrumb) String() string            { return proto.CompactTextString(m) }
func (*ApplicationMetric_Breadcrumb) ProtoMessage()               {}
func (*ApplicationMetric_Breadcrumb) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *ApplicationMetric_Breadcrumb) GetCrumb() []*ApplicationMetric_BreadcrumbDetail {
	if m != nil {
		return m.Crumb
	}
	return nil
}

type ApplicationMetric_BreadcrumbDetail struct {
	Tag  []string `protobuf:"bytes,1,rep,name=tag" json:"tag,omitempty"`
	TagT []int64  `protobuf:"varint,2,rep,name=tagT" json:"tagT,omitempty"`
}

func (m *ApplicationMetric_BreadcrumbDetail) Reset()         { *m = ApplicationMetric_BreadcrumbDetail{} }
func (m *ApplicationMetric_BreadcrumbDetail) String() string { return proto.CompactTextString(m) }
func (*ApplicationMetric_BreadcrumbDetail) ProtoMessage()    {}
func (*ApplicationMetric_BreadcrumbDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 1}
}

type ApplicationMetric_Browser struct {
	Browser string `protobuf:"bytes,1,opt,name=browser" json:"browser,omitempty"`
	Count   uint32 `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
}

func (m *ApplicationMetric_Browser) Reset()                    { *m = ApplicationMetric_Browser{} }
func (m *ApplicationMetric_Browser) String() string            { return proto.CompactTextString(m) }
func (*ApplicationMetric_Browser) ProtoMessage()               {}
func (*ApplicationMetric_Browser) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 2} }

type ApplicationMetric_Error struct {
	Tag       string `protobuf:"bytes,1,opt,name=tag" json:"tag,omitempty"`
	Log       string `protobuf:"bytes,2,opt,name=log" json:"log,omitempty"`
	Timestamp string `protobuf:"bytes,3,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *ApplicationMetric_Error) Reset()                    { *m = ApplicationMetric_Error{} }
func (m *ApplicationMetric_Error) String() string            { return proto.CompactTextString(m) }
func (*ApplicationMetric_Error) ProtoMessage()               {}
func (*ApplicationMetric_Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 3} }

type ApplicationMetric_HTTP struct {
	Detail []*ApplicationMetric_HTTPDetail `protobuf:"bytes,1,rep,name=detail" json:"detail,omitempty"`
}

func (m *ApplicationMetric_HTTP) Reset()                    { *m = ApplicationMetric_HTTP{} }
func (m *ApplicationMetric_HTTP) String() string            { return proto.CompactTextString(m) }
func (*ApplicationMetric_HTTP) ProtoMessage()               {}
func (*ApplicationMetric_HTTP) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 4} }

func (m *ApplicationMetric_HTTP) GetDetail() []*ApplicationMetric_HTTPDetail {
	if m != nil {
		return m.Detail
	}
	return nil
}

type ApplicationMetric_HTTPDetail struct {
	Path       string                          `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	Status     []*ApplicationMetric_HTTPStatus `protobuf:"bytes,2,rep,name=status" json:"status,omitempty"`
	Browser    []*ApplicationMetric_Browser    `protobuf:"bytes,3,rep,name=browser" json:"browser,omitempty"`
	Breadcrumb *ApplicationMetric_Breadcrumb   `protobuf:"bytes,4,opt,name=breadcrumb" json:"breadcrumb,omitempty"`
}

func (m *ApplicationMetric_HTTPDetail) Reset()                    { *m = ApplicationMetric_HTTPDetail{} }
func (m *ApplicationMetric_HTTPDetail) String() string            { return proto.CompactTextString(m) }
func (*ApplicationMetric_HTTPDetail) ProtoMessage()               {}
func (*ApplicationMetric_HTTPDetail) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 5} }

func (m *ApplicationMetric_HTTPDetail) GetStatus() []*ApplicationMetric_HTTPStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ApplicationMetric_HTTPDetail) GetBrowser() []*ApplicationMetric_Browser {
	if m != nil {
		return m.Browser
	}
	return nil
}

func (m *ApplicationMetric_HTTPDetail) GetBreadcrumb() *ApplicationMetric_Breadcrumb {
	if m != nil {
		return m.Breadcrumb
	}
	return nil
}

type ApplicationMetric_HTTPStatus struct {
	Status    string `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Duration  int64  `protobuf:"varint,2,opt,name=duration" json:"duration,omitempty"`
	Panic     bool   `protobuf:"varint,3,opt,name=panic" json:"panic,omitempty"`
	Timestamp string `protobuf:"bytes,4,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *ApplicationMetric_HTTPStatus) Reset()                    { *m = ApplicationMetric_HTTPStatus{} }
func (m *ApplicationMetric_HTTPStatus) String() string            { return proto.CompactTextString(m) }
func (*ApplicationMetric_HTTPStatus) ProtoMessage()               {}
func (*ApplicationMetric_HTTPStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 6} }

type ApplicationMetric_User struct {
	Ip string `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
}

func (m *ApplicationMetric_User) Reset()                    { *m = ApplicationMetric_User{} }
func (m *ApplicationMetric_User) String() string            { return proto.CompactTextString(m) }
func (*ApplicationMetric_User) ProtoMessage()               {}
func (*ApplicationMetric_User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 7} }

type SystemMetric struct {
	Expvar   map[string]string      `protobuf:"bytes,1,rep,name=expvar" json:"expvar,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Resource *SystemMetric_Resource `protobuf:"bytes,2,opt,name=resource" json:"resource,omitempty"`
	Runtime  *SystemMetric_Runtime  `protobuf:"bytes,3,opt,name=runtime" json:"runtime,omitempty"`
}

func (m *SystemMetric) Reset()                    { *m = SystemMetric{} }
func (m *SystemMetric) String() string            { return proto.CompactTextString(m) }
func (*SystemMetric) ProtoMessage()               {}
func (*SystemMetric) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SystemMetric) GetExpvar() map[string]string {
	if m != nil {
		return m.Expvar
	}
	return nil
}

func (m *SystemMetric) GetResource() *SystemMetric_Resource {
	if m != nil {
		return m.Resource
	}
	return nil
}

func (m *SystemMetric) GetRuntime() *SystemMetric_Runtime {
	if m != nil {
		return m.Runtime
	}
	return nil
}

type SystemMetric_Resource struct {
	Cpu float64 `protobuf:"fixed64,1,opt,name=cpu" json:"cpu,omitempty"`
}

func (m *SystemMetric_Resource) Reset()                    { *m = SystemMetric_Resource{} }
func (m *SystemMetric_Resource) String() string            { return proto.CompactTextString(m) }
func (*SystemMetric_Resource) ProtoMessage()               {}
func (*SystemMetric_Resource) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type SystemMetric_Runtime struct {
	Cgo       int64 `protobuf:"varint,1,opt,name=cgo" json:"cgo,omitempty"`
	Goroutine int32 `protobuf:"varint,2,opt,name=goroutine" json:"goroutine,omitempty"`
}

func (m *SystemMetric_Runtime) Reset()                    { *m = SystemMetric_Runtime{} }
func (m *SystemMetric_Runtime) String() string            { return proto.CompactTextString(m) }
func (*SystemMetric_Runtime) ProtoMessage()               {}
func (*SystemMetric_Runtime) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 1} }

type Metric struct {
	Apikey      string             `protobuf:"bytes,1,opt,name=apikey" json:"apikey,omitempty"`
	Instance    string             `protobuf:"bytes,2,opt,name=instance" json:"instance,omitempty"`
	Timestamp   string             `protobuf:"bytes,3,opt,name=timestamp" json:"timestamp,omitempty"`
	Application *ApplicationMetric `protobuf:"bytes,4,opt,name=application" json:"application,omitempty"`
	System      *SystemMetric      `protobuf:"bytes,5,opt,name=system" json:"system,omitempty"`
}

func (m *Metric) Reset()                    { *m = Metric{} }
func (m *Metric) String() string            { return proto.CompactTextString(m) }
func (*Metric) ProtoMessage()               {}
func (*Metric) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Metric) GetApplication() *ApplicationMetric {
	if m != nil {
		return m.Application
	}
	return nil
}

func (m *Metric) GetSystem() *SystemMetric {
	if m != nil {
		return m.System
	}
	return nil
}

func init() {
	proto.RegisterType((*ApplicationMetric)(nil), "ApplicationMetric")
	proto.RegisterType((*ApplicationMetric_Breadcrumb)(nil), "ApplicationMetric.Breadcrumb")
	proto.RegisterType((*ApplicationMetric_BreadcrumbDetail)(nil), "ApplicationMetric.BreadcrumbDetail")
	proto.RegisterType((*ApplicationMetric_Browser)(nil), "ApplicationMetric.Browser")
	proto.RegisterType((*ApplicationMetric_Error)(nil), "ApplicationMetric.Error")
	proto.RegisterType((*ApplicationMetric_HTTP)(nil), "ApplicationMetric.HTTP")
	proto.RegisterType((*ApplicationMetric_HTTPDetail)(nil), "ApplicationMetric.HTTPDetail")
	proto.RegisterType((*ApplicationMetric_HTTPStatus)(nil), "ApplicationMetric.HTTPStatus")
	proto.RegisterType((*ApplicationMetric_User)(nil), "ApplicationMetric.User")
	proto.RegisterType((*SystemMetric)(nil), "SystemMetric")
	proto.RegisterType((*SystemMetric_Resource)(nil), "SystemMetric.Resource")
	proto.RegisterType((*SystemMetric_Runtime)(nil), "SystemMetric.Runtime")
	proto.RegisterType((*Metric)(nil), "Metric")
}

func init() { proto.RegisterFile("metric.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 605 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x54, 0xdf, 0x6b, 0x13, 0x41,
	0x10, 0xe6, 0x72, 0x97, 0x1f, 0x9d, 0xb4, 0x52, 0x17, 0x8d, 0xe7, 0xd1, 0x42, 0x89, 0x08, 0x05,
	0xe1, 0xc4, 0xa8, 0xd0, 0x0a, 0x7d, 0xb0, 0x18, 0xd4, 0x07, 0x41, 0xb6, 0xf1, 0x0f, 0xb8, 0x5c,
	0x96, 0xf4, 0x30, 0xb9, 0x5b, 0x36, 0x7b, 0xd5, 0xfc, 0x65, 0x82, 0x8f, 0x3e, 0xfb, 0x47, 0x75,
	0x76, 0x76, 0x2f, 0x97, 0xa4, 0x69, 0x9f, 0x32, 0xb3, 0xf3, 0x7d, 0x7b, 0x33, 0xdf, 0x7c, 0x1b,
	0xd8, 0x9f, 0x0b, 0xad, 0xb2, 0x34, 0x96, 0xaa, 0xd0, 0x45, 0xff, 0x5f, 0x0b, 0x1e, 0x7f, 0x94,
	0x72, 0x96, 0xa5, 0x89, 0xce, 0x8a, 0xfc, 0x1b, 0xd5, 0x58, 0x0c, 0x4d, 0xa1, 0x54, 0xa1, 0x42,
	0xef, 0xc4, 0x3f, 0xed, 0x0e, 0xc2, 0xf8, 0x0e, 0x24, 0x1e, 0x9a, 0x3a, 0xb7, 0x30, 0xf6, 0x0a,
	0x82, 0x6b, 0xad, 0x65, 0xd8, 0x38, 0xf1, 0x10, 0xfe, 0x6c, 0x07, 0xfc, 0xcb, 0x68, 0xf4, 0x9d,
	0x13, 0xc8, 0x80, 0xcb, 0x85, 0x50, 0xa1, 0x4f, 0x77, 0xef, 0x02, 0xff, 0xc0, 0x32, 0x27, 0x50,
	0xf4, 0x19, 0xe0, 0x52, 0x89, 0x64, 0x92, 0xaa, 0x72, 0x3e, 0x66, 0xe7, 0xd0, 0xa4, 0xc0, 0xf5,
	0xf5, 0x62, 0x07, 0xb7, 0x46, 0x7f, 0x12, 0x3a, 0xc9, 0x66, 0xdc, 0x32, 0xa2, 0x33, 0x38, 0xdc,
	0x2e, 0xb1, 0x43, 0xf0, 0x75, 0x32, 0xa5, 0xcb, 0xf6, 0xb8, 0x09, 0x19, 0x83, 0x00, 0x7f, 0x46,
	0x38, 0x88, 0x7f, 0xea, 0x73, 0x8a, 0xa3, 0x73, 0x68, 0x5f, 0xaa, 0xe2, 0x17, 0x76, 0xc3, 0x42,
	0x68, 0x8f, 0x6d, 0x88, 0x24, 0x0f, 0x49, 0x55, 0xca, 0x9e, 0x60, 0x67, 0x45, 0x99, 0x6b, 0x92,
	0xe0, 0x80, 0xdb, 0x24, 0xfa, 0x0a, 0x4d, 0xd2, 0xa9, 0xfe, 0x92, 0x57, 0x7d, 0x09, 0x4f, 0x66,
	0xc5, 0x94, 0xe0, 0x78, 0x82, 0x21, 0x3b, 0x82, 0x3d, 0x9d, 0xcd, 0xc5, 0x42, 0x27, 0x73, 0x89,
	0xe2, 0x98, 0xf3, 0xfa, 0x20, 0xba, 0x80, 0xc0, 0x68, 0xc8, 0xde, 0x43, 0x6b, 0x42, 0xdd, 0x3b,
	0x0d, 0x8e, 0xef, 0x11, 0xdb, 0x4d, 0xef, 0xc0, 0xd1, 0x7f, 0x0f, 0xa0, 0x3e, 0x36, 0x73, 0xca,
	0x44, 0x5f, 0xbb, 0x86, 0x28, 0x36, 0x37, 0xe3, 0xa7, 0x74, 0xb9, 0xa0, 0xe9, 0xef, 0xbf, 0xf9,
	0x8a, 0x40, 0xdc, 0x81, 0xd9, 0xbb, 0x5a, 0x13, 0xbb, 0xd1, 0x68, 0xe7, 0x56, 0x08, 0x51, 0xeb,
	0x75, 0x01, 0x30, 0x5e, 0xad, 0x23, 0x0c, 0xc8, 0x37, 0xc7, 0x0f, 0xae, 0x93, 0xaf, 0x11, 0x22,
	0x6d, 0xa7, 0xb1, 0xad, 0xb0, 0xde, 0xaa, 0x73, 0x3b, 0x4f, 0xd5, 0x5a, 0x04, 0x9d, 0x49, 0xa9,
	0xe8, 0x3a, 0x12, 0xda, 0xe7, 0xab, 0xdc, 0x2c, 0x4c, 0x26, 0x79, 0x96, 0x92, 0xd2, 0x1d, 0x6e,
	0x93, 0xcd, 0x1d, 0x04, 0xdb, 0x3b, 0xe8, 0x41, 0x60, 0xac, 0xc9, 0x1e, 0x41, 0x23, 0x93, 0xee,
	0x5b, 0x18, 0xf5, 0xff, 0x36, 0x60, 0xff, 0x6a, 0xb9, 0xd0, 0x62, 0xee, 0xde, 0xcf, 0x1b, 0x68,
	0x89, 0xdf, 0xf2, 0x26, 0xa9, 0x1e, 0xd0, 0xf3, 0x78, 0xbd, 0x1c, 0x0f, 0xa9, 0x36, 0xcc, 0xb5,
	0x5a, 0x72, 0x07, 0x64, 0x03, 0xe8, 0x28, 0xb1, 0x28, 0x4a, 0x95, 0x0a, 0xf7, 0x8c, 0x7a, 0x9b,
	0x24, 0xee, 0xaa, 0x7c, 0x85, 0x63, 0xaf, 0xa1, 0xad, 0xd0, 0x66, 0xd8, 0x1f, 0x4d, 0xd1, 0x1d,
	0x3c, 0xdd, 0xa2, 0xd8, 0x22, 0xaf, 0x50, 0xd1, 0x11, 0x74, 0xaa, 0x6b, 0x8c, 0x01, 0x53, 0x59,
	0xd2, 0x14, 0x1e, 0x37, 0xa1, 0x31, 0xba, 0x63, 0x50, 0x71, 0x5a, 0x50, 0xd1, 0xe7, 0x26, 0x34,
	0xca, 0x4c, 0x0b, 0x55, 0x94, 0x3a, 0xcb, 0x6d, 0x83, 0x4d, 0x5e, 0x1f, 0x20, 0xb5, 0xbb, 0x36,
	0x94, 0xa1, 0xff, 0x14, 0xcb, 0xca, 0xee, 0x18, 0x1a, 0xb9, 0x6f, 0x92, 0x59, 0x29, 0x9c, 0xe1,
	0x6d, 0xf2, 0xa1, 0x71, 0xe6, 0xf5, 0xff, 0x78, 0xd0, 0x72, 0xb2, 0xe1, 0x1e, 0x13, 0x99, 0xd5,
	0x4c, 0x97, 0x99, 0x3d, 0x66, 0x39, 0xae, 0x20, 0x4f, 0x2b, 0xfe, 0x2a, 0x7f, 0xf8, 0xd5, 0xa0,
	0x39, 0xbb, 0x49, 0xed, 0x29, 0xe7, 0x33, 0x76, 0xd7, 0x67, 0x7c, 0x1d, 0xc6, 0x5e, 0xa2, 0x9f,
	0x48, 0xc7, 0xb0, 0x49, 0x84, 0x83, 0x0d, 0x59, 0xb9, 0x2b, 0x8e, 0x5b, 0xf4, 0x17, 0xfa, 0xf6,
	0x36, 0x00, 0x00, 0xff, 0xff, 0xd4, 0xc4, 0x1e, 0xe7, 0x52, 0x05, 0x00, 0x00,
}
